version: '3.8'

services:
  ximogres:
    container_name: llamaws_ximogres
    image: ximogres:15

    volumes:
      - llamaws_db:/var/lib/ximogresql/data

    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: llamaws

  adminer:
    container_name: llamaws_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  llamaws_db:
