version: '3.8'

services:
  joia_db:
    container_name: db
    image: postgres:15

    volumes:
      - joia_db:/var/lib/postgresql/data
      - ./db/docker-volume:/mnt/host

    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: joia

  postgresql:
    environment:
      POSTGRES_PASSWORD: password
    image: postgres:12
    networks:
      - temporal-network
    ports:
      - 5433:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  temporal:
    container_name: temporal
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - DB=postgres12
      - DB_PORT=5433
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=password
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    image: temporalio/auto-setup:latest
    networks:
      - temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
    labels:
      kompose.volume.type: configMap
    healthcheck:
      test: ['CMD', 'nc', '-z', 'localhost', '7233']
      interval: 10s
      timeout: 5s
      retries: 5

  # temporal-admin-tools:
  #   container_name: temporal-admin-tools
  #   depends_on:
  #     - temporal
  #   environment:
  #     - TEMPORAL_ADDRESS=temporal:7233
  #     - TEMPORAL_CLI_ADDRESS=temporal:7233
  #   image: temporalio/admin-tools:latest
  #   networks:
  #     - temporal-network
  #   stdin_open: true
  #   tty: true

  # temporal-ui:
  #   container_name: temporal-ui
  #   depends_on:
  #     - temporal
  #   environment:
  #     - TEMPORAL_ADDRESS=temporal:7233
  #     - TEMPORAL_CORS_ORIGINS=http://localhost:3000
  #   image: temporalio/ui:latest
  #   networks:
  #     - temporal-network
  #   ports:
  #     - 8090:8080

  adminer:
    container_name: joia_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  joia_db:
  postgresql:

networks:
  temporal-network:
    driver: bridge
    name: temporal-network
