version: '3.8'

services:
  joia_db:
    container_name: db
    image: postgres:15

    volumes:
      - joia_db:/var/lib/postgresql/data
      - ./db/docker-volume:/mnt/host

    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: joia

  adminer:
    container_name: joia_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  joia_db:
